routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', 'TampilanController@index');
Route::resource('/', 'TampilanController');


Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('/services',  'ServiceController');
Route::resource('/category', 'CategoryController');
Route::resource('/tag', 'TagController');
Route::resource('/post', 'PostController');
Route::resource('/user', 'UserController');
Route::resource('/about', 'AboutController');
Route::resource('/owner', 'OwnerController');

app/Owner.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Owner extends Model
{
	 protected $table = 'owner';
   protected $fillable = ['judul','content','gambar'];

}

app/Http/Controllers/OwnerController.php
<?php

namespace App\Http\Controllers;
use DB;
use Illuminate\Http\Request;
Use App\Owner;

class OwnerController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */

     public function __construct()
    {
        $this->middleware('auth');
    }
    public function index()

    {
        $owner = Owner::all();
        return view('owner.index', compact('owner'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
         return view('owner.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
         $request->validate([
            'judul' => 'required|unique:owner',
            'content' => 'required',
              'gambar' => 'required'
        ]);

         $gambar = $request->gambar;
         $new_gambar = time().$gambar->getClientOriginalName();

        $owner = Owner::create([
            "judul" => $request["judul"],
             "content" => $request["content"],
             "gambar" => 'uploads/owner/'.$new_gambar
             
        ]);


        $gambar->move('uploads/owner/', $new_gambar);

         return redirect('/owner')->with('success', 'owner Berhasil Disimpan');

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $show = Owner::find($id);

        return view('owner.show', compact('show'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
       $owner = Owner::find($id);

        return view('owner.edit', compact('owner'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {

          
        $owner = Owner::findorfail($id);
           if ($request->has('gambar')) {
            $gambar = $request->gambar;
            $new_gambar = time().$gambar->getClientOriginalName();
            $gambar->move('uploads/owner/', $new_gambar);

        $owner_data = [
            "judul" => $request["judul"],
             "content" => $request["content"],
             "gambar" => 'uploads/owner/'.$new_gambar
        ];
        }
        else{
        $owner_data = [
              "judul" => $request["judul"],
             "content" => $request["content"],
        ];
        }
          $owner->update($owner_data);
        //         $gambar = $request->gambar;
        //         $new_gambar = time().$gambar->getClientOriginalName();
         
           

        //  $update = Owner::where('id', $id)->update([
        //    "judul" => $request["judul"],
        //      "content" => $request["content"],
        //      "gambar" => 'uploads/owner/'.$new_gambar

        // ]);

        //    $gambar->move('uploads/owner/', $new_gambar);
        return redirect('/owner')->with('success', 'owner Berhasil Diupdate');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
         Owner::destroy($id);
        return redirect('/owner')->with('success', 'owner Berhasil Dihapus');
    }
}

resources/views/owner/create.blade.php
@extends('layouts.master')
@section('content')
	<div class="m-3">
	<div class="card card-primary">
	             
	              <div class="card-header">
	                <h3 class="card-title">Create owner</h3>
	              </div>
	              <!-- /.card-header -->
	              <!-- form start -->
	              <form role="form" action="/owner" method="POST" enctype="multipart/form-data">
	              	@csrf
	                <div class="card-body">
	                  <div class="form-group">
	                    <label for="judul">Nama</label>
	                    <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', '')}}" placeholder="Masukkan Nama" required>
	                     @error('judul')
                    	<div class="alert alert-danger">
                        {{ $message }}
                    	</div>
                		@enderror
	                  </div>

	                  <div class="form-group">
	                    <label for="content">Deskripsi</label>
	                    <input type="text" class="form-control" id="content" name="content" value="{{ old('content', '')}}" placeholder="Masukkan Deskripsi" required>
	                    @error('content')
                   		 <div class="alert alert-danger">
                        {{ $message }}
                    	</div>
              			 @enderror
	                  </div>

	                  <div class="form-group">
                    <label for="gambar">Gambar</label>

                    <div class="custom-file">
                      <input type="file" class="form-control" id="gambar" name="gambar" placeholder="gambar" required>
                      <label class="custom-file-label" for="gambar">Choose file</label>
                    </div>
                  </div>
	                 
	                 
	                 
	                </div>
	                <!-- /.card-body -->

	                <div class="card-footer">
	                  <button type="submit" class="btn btn-primary">Create</button>
	                </div>
	              </form>
	          
	        </div>
	    </div>

@endsection

resources/views/owner/edit.blade.php
@extends('layouts.master')
@section('content')
	<div class="m-3">
	<div class="card card-primary">
	             
	              <div class="card-header">
	                <h3 class="card-title">Edit owner {{$owner->id}}</h3>
	              </div>
	              <!-- /.card-header -->
	              <!-- form start -->
	              <form role="form" action="/owner/{{$owner->id}}" method="POST"  enctype="multipart/form-data">
	              	@csrf
	              	@method('PUT')
	                <div class="card-body">
	                  <div class="form-group">
	                    <label for="judul">Nama</label>
	                    <input type="text" class="form-control" id="judul" name="judul" value="{{ old('judul', $owner->judul)}}" placeholder="Masukkan Nama" required>
	                     @error('judul')
                    	<div class="alert alert-danger">
                        {{ $message }}
                    	</div>
                		@enderror
	                  </div>

	                  <div class="form-group">
	                    <label for="content">Deskripsi</label>
	                    <input type="text" class="form-control" id="content" name="content" value="{{ old('content', $owner->content)}}" placeholder="Masukkan Deskripsi" required>
	                    @error('content')
                   		 <div class="alert alert-danger">
                        {{ $message }}  
                    	</div>
              			 @enderror
	                  </div>

	                  <div class="form-group">
                    <label for="gambar">Gambar</label>
                     <div class="form-group">
                     	<img src="	{{ asset($owner->gambar) }}" height="100px">
                     </div>
                    <div class="custom-file">
                      <input type="file" class="form-control" id="gambar" name="gambar" value="{{ old('gambar', $owner->gambar)}}"  placeholder="gambar" >
                      <label class="custom-file-label" for="gambar">Choose file</label>
                    </div>
                  </div>
	                 
	                 
	                 
	                </div>
	                <!-- /.card-body -->

	                <div class="card-footer">
	                  <button type="submit" class="btn btn-primary">Update</button>
	                </div>
	              </form>
	          
	        </div>
	    </div>

@endsection

resources/views/owner/index.blade.php
@extends('layouts.master')
@section('content')
	<div class="m-3">
	<div class="card">
              <div class="card-header">
                <h3 class="card-title">Daftar Nama Owner</h3>

                <div class="card-tools">
		      <a href="{{ route('owner.create')}}" class="btn btn-primary">Tambah Owner</a>
                </div>
              </div>
              <!-- /.card-header -->
              <div class="card-body p-0">
              	@if(session('success'))
              	<div class="alert alert-success m-3">
              			{{ session('success') }}
				<button type="button" class="close" data-dismiss="alert" aria-label="Close">
				<span aria-hidden="true">&times;</span>
				</button>
              		
              	</div>
              	@endif
                <table class="table">
                  <thead>
                    <tr>
                      <th style="width: 10px">#</th>
                      <th>Nama</th>
                      <th>Deskripsi</th>
                      <th>Gambar</th>
                      
                      <th style="width: 40px">Action</th>
                    </tr>
                  </thead>
                  <tbody>
                      @forelse ($owner as $key=>$value)
                    <tr>
                        <td>{{$key + 1}}</th>
                        <td>{{$value->judul}}</td>
                        <td>{{$value->content}}</td>
                        <td><img src="{{ asset($value->gambar) }}" class="img-fluid" style="max-height: 100px; display: block; margin: auto; width: 100px;"></td>
                        <td style="display: flex">
                            <a href="{{ route('owner.show', ['owner' => $value->id] )}}" class="btn btn-info btn-sm my-1 mr-1">Show</a>
                            <a href="{{ route('owner.edit', ['owner' => $value->id] )}}" class="btn btn-primary btn-sm my-1 mr-1">Edit</a>
                            <form action="{{ route('owner.destroy', ['owner' => $value->id] )}}" method="POST">
                                @csrf
                                @method('DELETE')
                                <input type="submit" class="btn btn-danger btn-sm my-1 mr-1" value="Delete">
                            </form>
                        </td>
                    </tr>
                @empty
                    <tr colspan="4">
                        <td>No data</td>
                    </tr>  
                @endforelse            
                  </tbody>
                </table>
              </div>
              <!-- /.card-body -->
            </div>
        </div>

@endsection

resources/views/owner/show.blade.php
@extends('layouts.master')
@section('content')
<div class="m-3">
	<div class="card">
              <div class="card-header">
                <h3 class="card-title">{{ $show->judul }}</h3>
              </div>
              <!-- /.card-header -->
              <div class="card-body text-center">
               
                <img src="{{asset($show->gambar)}}"  style="width: 100px; ">
              	
                <p style="margin-top: 20px">{{ $show->content }}</p>
               
              <!-- /.card-body -->

            </div>
        </div>
    </div>

@endsection